title: E-Portfolio Home
email: craignorris10@gmail.com
author: Craig Norris
description: >
  MSc Cyber Security e-Portfolio highlighting key insights, reflections, and achievements.

baseurl: ""
url: ""
markdown: kramdown
kmarkdown:
  input: GFM

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

yat:
  date_format: "%b %d, %Y"
